[project]
name = "aoc-py"
version = "0.1.0"
description = "Advent of Code in python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astar>=0.99",
    "fastapi[standard]>=0.115.6",
]
